package representation;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JButton;
import userInterface.ControlFrame;

/**
 *
 * @author Mintxoo - mintxosola@gmail.com
 */
public class SpeedDrawing extends javax.swing.JFrame {
    public ControlFrame control;

    /**
     * Creates new form Speed
     * @param control
     */
    public SpeedDrawing(ControlFrame control) {
        initComponents();
        this.control = control;
    }
    
    public void run() throws InterruptedException{
        while(true){
        }
    }
    
    public void updateDrawing (){
        repaint();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(".");

        jLabel2.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics g) {
        if (control.speedMessage != null) {
            super.paint(g);
            g.setColor(Color.RED);

            int dim;
            int verticalSpacing = 120, horizontalSpacing = 120;
            int hDist = 75, vDist = 75;
            int buttonHeight = 60, buttonWidth = 60;

            for (int i = 0; i < control.rows; i++) {
                for (int j = 0; j < control.cols; j++) {
                    int start = (i * control.cols + j) * 6 + 1;
                    int end = start + 5;

                    for (int k = start; k <= end; k++) {
                        if(k <= control.server.clients.size()*6){
                            int xOffset = hDist + j * (horizontalSpacing);
                            int yOffset = vDist + i * (verticalSpacing + buttonHeight);
                            dim = (int) (control.speedMessage[k - 1] * 0.6);
                            
                            // Lógica de ventiladores impares y pares
                            if (k % 2 != 0) {  // Ventilador impar
                                g.fillOval(xOffset-dim/2, yOffset + ((k - start) / 2) * buttonHeight-dim/2, dim, dim);
                            } else {  // Ventilador par
                                g.fillOval(xOffset + buttonWidth-dim/2, yOffset + ((k - start) / 2) * buttonHeight-dim/2, dim, dim);
                            }
                        }
                    }
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
