package extra;
import java.io.File;
import userInterface.ControlFrame;

/**
 *
 * @author Mintxoo - mintxosola@gmail.com
 */
public class Principal extends javax.swing.JFrame {

    public ControlFrame control;
    
    public Principal(ControlFrame control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropTarget1 = new java.awt.dnd.DropTarget();
        dropTarget2 = new java.awt.dnd.DropTarget();
        dropTarget3 = new java.awt.dnd.DropTarget();
        dropTarget4 = new java.awt.dnd.DropTarget();
        dropTarget5 = new java.awt.dnd.DropTarget();
        dropTarget6 = new java.awt.dnd.DropTarget();
        dropTarget7 = new java.awt.dnd.DropTarget();
        label = new javax.swing.JLabel();

        dropTarget7.setComponent(label);
        try {
            dropTarget7.addDropTargetListener(new java.awt.dnd.DropTargetListener() {
                public void dragEnter(java.awt.dnd.DropTargetDragEvent evt) {
                }
                public void dragExit(java.awt.dnd.DropTargetEvent evt) {
                }
                public void dragOver(java.awt.dnd.DropTargetDragEvent evt) {
                }
                public void drop(java.awt.dnd.DropTargetDropEvent evt) {
                    dropTarget7Drop(evt);
                }
                public void dropActionChanged(java.awt.dnd.DropTargetDragEvent evt) {
                }
            });
        } catch (java.util.TooManyListenersException e1) {
            e1.printStackTrace();
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        label.setBackground(new java.awt.Color(255, 153, 153));
        label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public File[] files;
    public boolean end = false;
    
    private void dropTarget7Drop(java.awt.dnd.DropTargetDropEvent evt) {//GEN-FIRST:event_dropTarget7Drop
        files = Index.getDropFiles(evt);
        for (File file : files){
            System.out.println("File "+file.getName()+" droped");
            control.funFile = file;
        }
        end = true;
        dispose();
    }//GEN-LAST:event_dropTarget7Drop


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.dnd.DropTarget dropTarget1;
    private java.awt.dnd.DropTarget dropTarget2;
    private java.awt.dnd.DropTarget dropTarget3;
    private java.awt.dnd.DropTarget dropTarget4;
    private java.awt.dnd.DropTarget dropTarget5;
    private java.awt.dnd.DropTarget dropTarget6;
    private java.awt.dnd.DropTarget dropTarget7;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
