package representation;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.Socket;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import userInterface.ControlFrame;

/**
 *
 * @author Mintxoo - mintxosola@gmail.com
 */
public class PressureSensor extends javax.swing.JFrame {
    public ControlFrame control;
    InputStream in;
    
    public float full_scale_psi = (float) 0.1445092;
    public float full_scale_pa = (float) (full_scale_psi * 6894.76);
            
    public PressureSensor(ControlFrame c) {
        initComponents();
        this.control = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        popupMenu1 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        showPressure = new java.awt.List();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pressure Sensor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(showPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(showPressure, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @throws InterruptedException
     * @throws IOException
     */
    public void run() throws InterruptedException, IOException {
        connectPressureServer();
        byte[] packet = new byte[75]; // Buffer para almacenar el paquete recibido

        while (true) {
            int bytesRead = in.read(packet, 0, packet.length);
            if (bytesRead == -1) {
                break;
            }

            try {
                PacketData parsedData = parsePacket(packet);
                System.out.printf("[%s]\n", parsedData.timestamp.toString());
                for (int i = 0; i < parsedData.pressures.length; i++) {
                    System.out.printf("%.2f, ", parsedData.pressures[i]);
                }
                System.out.println("\n--------------------");

                Thread.sleep(10);
            } catch (Exception e) {
                System.err.println("Error parsing packet: " + e.getMessage());
            }
        }
    }

    public void connectPressureServer() throws InterruptedException {
        if (control.pressureSensorIP == null || control.pressureSensorPort == -1) {
            NewPSensor ps = new NewPSensor(control);
            ps.run();
            ps.dispose();
        }
        try {
            showPressure.add("----Buscando Conexión----");
            Socket socket = new Socket(control.pressureSensorIP, control.pressureSensorPort);
            in = socket.getInputStream();
            showPressure.add("----Conectado correctamente----");
            System.out.println("Se conecto al socket "+socket);
        } catch (IOException e) {
            System.out.println("No se pudo conectar al host");
            System.err.println("----No se pudo conectar al host: " + control.pressureSensorIP+"----");
        }
    }

    private PacketData parsePacket(byte[] packet) throws IOException {
        // Verify header
        ByteBuffer buffer = ByteBuffer.wrap(packet);
        buffer.order(ByteOrder.LITTLE_ENDIAN);
        int header = buffer.getShort(0) & 0xFFFF;
        if (header != 0x00FF) {
            throw new IllegalArgumentException("Invalid packet: incorrect header");
        }

        // Parse timestamp (two 32-bit numbers)
        long seconds = buffer.getInt(3) & 0xFFFFFFFFL;
        long subseconds = buffer.getInt(7) & 0xFFFFFFFFL;
        LocalDateTime timestamp = LocalDateTime.ofEpochSecond(seconds, (int) (subseconds * 1000), ZoneOffset.UTC);

        // Parse 32 channels (16-bit integers)
        double[] pressures = new double[32];
        for (int i = 0; i < 32; i++) {
            int rawValue = buffer.getShort(11 + i * 2) & 0xFFFF;
            pressures[i] = (rawValue - 32768) * (full_scale_pa / 32768);
        }

        return new PacketData(timestamp, pressures);
    }

    // Helper class to store parsed data
    private static class PacketData {
        LocalDateTime timestamp;
        double[] pressures;

        public PacketData(LocalDateTime timestamp, double[] pressures) {
            this.timestamp = timestamp;
            this.pressures = pressures;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.List showPressure;
    // End of variables declaration//GEN-END:variables
}
