package userInterface;

import representation.Fan;
import functionality.Functionality;
import functionality.Index;
import representation.PressureSensor;
import functionality.Principal;
import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import raspberryserver.InterfaceServer;


import java.io.File;
import javax.swing.JFrame;
import representation.SpeedDrawing;


/**
 *
 * @author Mintxoo - mintxosola@gmail.com
 */
public class ControlFrame extends javax.swing.JFrame {
    public int activeFan = 0;
    public InterfaceServer server;
    
    public List<Fan> fanButtons = new LinkedList<>();
    public List<Functionality> functionalityList = new LinkedList<>();
    public int[] speedMessage;
    public SpeedDrawing speedDrawing;
    public boolean functionalityExecuting = false;
    
    public File funFile = null;
    public Index index = new Index();
    public Functionality functionality;
    public boolean firstTime = true;
    public String pressureSensorIP = null;
    public int pressureSensorPort = -1;
    
    
    /**
     * Creates new form MainFrame
     * @param server
     */
    public ControlFrame(InterfaceServer server) {
        initComponents();
        this.server = server;
    }
    
    public void setSpeedInstance(SpeedDrawing speedDrawing) {
        this.speedDrawing = speedDrawing;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        jLabel2 = new javax.swing.JLabel();
        speedSlider = new javax.swing.JSlider();
        showSpeed = new javax.swing.JLabel();
        updateSpeed = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numActiveFans = new javax.swing.JLabel();
        selectedFan = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        currentSpeed = new javax.swing.JLabel();
        stopAllFans = new javax.swing.JButton();
        fan1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fan2 = new javax.swing.JButton();
        fan3 = new javax.swing.JButton();
        fan4 = new javax.swing.JButton();
        fan5 = new javax.swing.JButton();
        fan6 = new javax.swing.JButton();
        fan7 = new javax.swing.JButton();
        fan8 = new javax.swing.JButton();
        fan9 = new javax.swing.JButton();
        fan10 = new javax.swing.JButton();
        fan11 = new javax.swing.JButton();
        fan12 = new javax.swing.JButton();
        fan13 = new javax.swing.JButton();
        fan14 = new javax.swing.JButton();
        fan15 = new javax.swing.JButton();
        fan16 = new javax.swing.JButton();
        fan17 = new javax.swing.JButton();
        fan18 = new javax.swing.JButton();
        fan19 = new javax.swing.JButton();
        fan20 = new javax.swing.JButton();
        fan21 = new javax.swing.JButton();
        fan22 = new javax.swing.JButton();
        fan23 = new javax.swing.JButton();
        fan24 = new javax.swing.JButton();
        addFunctionality = new javax.swing.JButton();
        funExecution = new javax.swing.JButton();
        stopFun = new javax.swing.JButton();
        executing = new javax.swing.JLabel();
        funPreview = new javax.swing.JButton();
        pressureSensor = new javax.swing.JButton();
        funAction = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        speedSlider.setMajorTickSpacing(100);
        speedSlider.setPaintLabels(true);
        speedSlider.setPaintTicks(true);
        speedSlider.setValue(0);
        speedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                speedSliderStateChanged(evt);
            }
        });

        showSpeed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showSpeed.setText("0");

        updateSpeed.setBackground(new java.awt.Color(255, 204, 255));
        updateSpeed.setText("UPDATE");
        updateSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSpeedActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("WIND TUNEL GUI");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Active fans:");

        numActiveFans.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numActiveFans.setText("x fans");

        selectedFan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectedFan.setText("Selected fan");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Current Speed:");

        currentSpeed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        currentSpeed.setText("0 %");

        stopAllFans.setBackground(new java.awt.Color(255, 255, 153));
        stopAllFans.setText("STOP ALL");
        stopAllFans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopAllFansMouseClicked(evt);
            }
        });

        fan1.setText("1");
        fan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("FANS SCHEMA");

        fan2.setText("2");
        fan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan2ActionPerformed(evt);
            }
        });

        fan3.setText("3");
        fan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan3ActionPerformed(evt);
            }
        });

        fan4.setText("4");
        fan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan4ActionPerformed(evt);
            }
        });

        fan5.setText("5");
        fan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan5ActionPerformed(evt);
            }
        });

        fan6.setText("6");
        fan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan6ActionPerformed(evt);
            }
        });

        fan7.setText("7");
        fan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan7ActionPerformed(evt);
            }
        });

        fan8.setText("8");
        fan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan8ActionPerformed(evt);
            }
        });

        fan9.setText("9");
        fan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan9ActionPerformed(evt);
            }
        });

        fan10.setText("10");
        fan10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan10ActionPerformed(evt);
            }
        });

        fan11.setText("11");
        fan11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan11ActionPerformed(evt);
            }
        });

        fan12.setText("12");
        fan12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan12ActionPerformed(evt);
            }
        });

        fan13.setText("13");
        fan13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan13ActionPerformed(evt);
            }
        });

        fan14.setText("14");
        fan14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan14ActionPerformed(evt);
            }
        });

        fan15.setText("15");
        fan15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan15ActionPerformed(evt);
            }
        });

        fan16.setText("16");
        fan16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan16ActionPerformed(evt);
            }
        });

        fan17.setText("17");
        fan17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan17ActionPerformed(evt);
            }
        });

        fan18.setText("18");
        fan18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan18ActionPerformed(evt);
            }
        });

        fan19.setText("19");
        fan19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan19ActionPerformed(evt);
            }
        });

        fan20.setText("20");
        fan20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan20ActionPerformed(evt);
            }
        });

        fan21.setText("21");
        fan21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan21ActionPerformed(evt);
            }
        });

        fan22.setText("22");
        fan22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan22ActionPerformed(evt);
            }
        });

        fan23.setText("23");
        fan23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan23ActionPerformed(evt);
            }
        });

        fan24.setText("24");
        fan24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fan24ActionPerformed(evt);
            }
        });

        addFunctionality.setText("Add Functionality File");
        addFunctionality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFunctionalityActionPerformed(evt);
            }
        });

        funExecution.setText("Execute Functionality");
        funExecution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funExecutionActionPerformed(evt);
            }
        });

        stopFun.setText("Stop Execution");
        stopFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopFunActionPerformed(evt);
            }
        });

        funPreview.setText("Execute Preview");
        funPreview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funPreviewMouseClicked(evt);
            }
        });

        pressureSensor.setBackground(new java.awt.Color(255, 153, 153));
        pressureSensor.setText("Show Pressure");
        pressureSensor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pressureSensorMouseClicked(evt);
            }
        });

        funAction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        funAction.setText("functionality info");
        funAction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fan17, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fan18, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(fan23, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fan24, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fan13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(fan14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fan5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(fan6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fan3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(fan4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(fan15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(fan16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(fan21, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fan7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fan9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fan11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fan19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fan10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fan12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fan20, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fan22, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fan8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fan1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fan2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numActiveFans, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(addFunctionality))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(139, 139, 139)
                                            .addComponent(updateSpeed)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(showSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(79, 79, 79)
                                            .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(13, 13, 13))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(stopFun)
                                            .addGap(14, 14, 14))
                                        .addComponent(funPreview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selectedFan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(pressureSensor)
                                        .addGap(67, 67, 67))
                                    .addComponent(funAction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(funExecution, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(stopAllFans)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(executing, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(149, Short.MAX_VALUE)
                        .addComponent(executing))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(selectedFan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(currentSpeed)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(numActiveFans))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fan1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fan3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fan5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fan13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fan15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fan17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fan24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateSpeed)
                            .addComponent(showSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pressureSensor)
                        .addGap(33, 33, 33)
                        .addComponent(addFunctionality)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(funExecution, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(funPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(funAction)
                        .addGap(12, 12, 12)
                        .addComponent(stopFun)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stopAllFans)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void speedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_speedSliderStateChanged
        showSpeed.setText(""+speedSlider.getValue());
    }//GEN-LAST:event_speedSliderStateChanged

    private void updateSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSpeedActionPerformed
        if(!functionalityExecuting){
            boolean anySelected = false;
            for (int i = 0; i < fanButtons.size(); i++){
                if(fanButtons.get(i).selected){
                    anySelected = true;
                    speedMessage[i] = speedSlider.getValue();
                    fanButtons.get(i).speed = speedSlider.getValue();
                }
            }
            if (anySelected){
                server.updateSpeed(speedMessage);
                speedDrawing.updateDrawing();
                currentSpeed.setText(""+speedSlider.getValue());
            }
        }
    }//GEN-LAST:event_updateSpeedActionPerformed

    private void stopAllFansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopAllFansMouseClicked
        for (int i = 0; i < fanButtons.size(); i++){
            speedMessage[i] = 0;
            fanButtons.get(i).speed = 0;
        }
        server.updateSpeed(speedMessage);
        speedDrawing.updateDrawing();
        currentSpeed.setText("0");
        speedSlider.setValue(0);
    }//GEN-LAST:event_stopAllFansMouseClicked

    private void fan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan2ActionPerformed
        activeFan = 1;
        fanControl(activeFan);
    }//GEN-LAST:event_fan2ActionPerformed

    private void fan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan3ActionPerformed
        activeFan = 2;
        fanControl(activeFan);
    }//GEN-LAST:event_fan3ActionPerformed

    private void fan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan4ActionPerformed
        activeFan = 3;
        fanControl(activeFan);
    }//GEN-LAST:event_fan4ActionPerformed

    private void fan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan5ActionPerformed
        activeFan = 4;
        fanControl(activeFan);
    }//GEN-LAST:event_fan5ActionPerformed

    private void fan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan6ActionPerformed
        activeFan = 5;
        fanControl(activeFan);
    }//GEN-LAST:event_fan6ActionPerformed

    private void fan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan7ActionPerformed
        activeFan = 6;
        fanControl(activeFan);
    }//GEN-LAST:event_fan7ActionPerformed

    private void fan8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan8ActionPerformed
        activeFan = 7;
        fanControl(activeFan);
    }//GEN-LAST:event_fan8ActionPerformed

    private void fan9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan9ActionPerformed
        activeFan = 8;
        fanControl(activeFan);
    }//GEN-LAST:event_fan9ActionPerformed

    private void fan10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan10ActionPerformed
        activeFan = 9;
        fanControl(activeFan);
    }//GEN-LAST:event_fan10ActionPerformed

    private void fan11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan11ActionPerformed
        activeFan = 10;
        fanControl(activeFan);
    }//GEN-LAST:event_fan11ActionPerformed

    private void fan12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan12ActionPerformed
        activeFan = 11;
        fanControl(activeFan);
    }//GEN-LAST:event_fan12ActionPerformed

    private void fan13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan13ActionPerformed
        activeFan = 12;
        fanControl(activeFan);
    }//GEN-LAST:event_fan13ActionPerformed

    private void fan14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan14ActionPerformed
        activeFan = 13;
        fanControl(activeFan);
    }//GEN-LAST:event_fan14ActionPerformed

    private void fan15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan15ActionPerformed
        activeFan = 14;
        fanControl(activeFan);
    }//GEN-LAST:event_fan15ActionPerformed

    private void fan16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan16ActionPerformed
        activeFan = 15;
        fanControl(activeFan);
    }//GEN-LAST:event_fan16ActionPerformed

    private void fan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan1ActionPerformed
        activeFan = 0;
        fanControl(activeFan);
    }//GEN-LAST:event_fan1ActionPerformed

    private void fan17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan17ActionPerformed
        activeFan = 16;
        fanControl(activeFan);
    }//GEN-LAST:event_fan17ActionPerformed

    private void fan18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan18ActionPerformed
        activeFan = 17;
        fanControl(activeFan);
    }//GEN-LAST:event_fan18ActionPerformed

    private void fan19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan19ActionPerformed
        activeFan = 18;
        fanControl(activeFan);
    }//GEN-LAST:event_fan19ActionPerformed

    private void fan20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan20ActionPerformed
        activeFan = 19;
        fanControl(activeFan);
    }//GEN-LAST:event_fan20ActionPerformed

    private void fan21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan21ActionPerformed
        activeFan = 20;
        fanControl(activeFan);
    }//GEN-LAST:event_fan21ActionPerformed

    private void fan22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan22ActionPerformed
        activeFan = 21;
        fanControl(activeFan);
    }//GEN-LAST:event_fan22ActionPerformed

    private void fan23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan23ActionPerformed
        activeFan = 22;
        fanControl(activeFan);
    }//GEN-LAST:event_fan23ActionPerformed

    private void fan24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fan24ActionPerformed
        activeFan = 23;
        fanControl(activeFan);
    }//GEN-LAST:event_fan24ActionPerformed

    private void addFunctionalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFunctionalityActionPerformed
        try {
            funFile = null;
            Principal principal = new Principal(this);
            principal.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            index.getFunFile(principal);
            firstTime = true;
        } catch (Exception e) {
            System.out.println("Error adding functionality file");
            e.printStackTrace();
        }
    }//GEN-LAST:event_addFunctionalityActionPerformed

    private static String getFileExtension(String fileName) {
        int lastDotIndex = fileName.lastIndexOf('.');
        if (lastDotIndex > 0) {
            return fileName.substring(lastDotIndex + 1);
        }
        return "";
    }
    
    private void funExecutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funExecutionActionPerformed
        try {
            functionality = new Functionality(this, speedDrawing,true);
            functionalityList.add(functionality);
            functionality.start();
            if(!getFileExtension(funFile.getName()).equals("xlsx")){
                functionalityExecuting = false;
                funAction.setText("Wrong file");
            }else{
                functionalityExecuting = true;
                funAction.setText("Functionality is executing... please wait");
            }
            
        } catch (Exception ex) {
            System.out.println("Error reading functionality file");
            funAction.setText("Error reading functionality file");
        }
    }//GEN-LAST:event_funExecutionActionPerformed

    private void stopFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopFunActionPerformed
        try{
            for (Functionality f : functionalityList) {
                f.interrupt();
            }
            functionalityExecuting = false;
            funAction.setText("No functionality executing");
        }catch(Exception e){
            System.out.println("Error on the stop of the functionality execution");
        }
        
    }//GEN-LAST:event_stopFunActionPerformed

    private void funPreviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funPreviewMouseClicked
        try {
            SpeedDrawing speedDrawing_aux = new SpeedDrawing(this);
            speedDrawing_aux.setVisible(true);
            speedDrawing_aux.setTitle("PREVIEW");
            speedDrawing_aux.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            speedDrawing_aux.setResizable(false);
            speedDrawing_aux.setLocation(500, 100);
            
            functionality = new Functionality(this, speedDrawing_aux,false);
            functionalityList.add(functionality);
            functionality.start();
            functionalityExecuting = true;
            funAction.setText("Preview is executing...");
            
        } catch (Exception ex) {
            System.out.println("Error reading functionality file");
            funAction.setText("Error reading functionality file");
        }
    }//GEN-LAST:event_funPreviewMouseClicked

    
    
    private void pressureSensorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pressureSensorMouseClicked
        try {
           Thread pressureThread = new Thread(() -> {
                PressureSensor pressure = new PressureSensor(this);
                pressure.setVisible(true);
                pressure.setTitle("PRESSURE");
                pressure.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                pressure.setResizable(false);
                pressure.setLocation(800, 200);
               try {
                   pressure.run();
               } catch (Exception e) {System.out.println("Error with the sensor");}
            });
            pressureThread.start();
            
        } catch (Exception ex) {
            System.out.println("Error showing pressure sensor info");
        }
    }//GEN-LAST:event_pressureSensorMouseClicked

    
    
    public void run() throws InterruptedException{
        enterFans(fanButtons);
        int cant = server.clients.size();
        setFansColor(cant,fanButtons);
        funExecution.setEnabled(false);
        funPreview.setEnabled(false);
        stopFun.setEnabled(false);
        while(true){
            Thread.sleep(50);
            if(funAction.getText().equals("No functionality executing")){
                functionalityExecuting = false;
            }
            
            if(funFile != null & firstTime){
                funAction.setText("File "+funFile.getName()+" added");
                funExecution.setEnabled(true);
                funPreview.setEnabled(true);
                stopFun.setEnabled(true);
                firstTime = false;
            }else if (funFile == null){
                funAction.setText("No file added");
            }
        }
    }
    
    public void enterFans(List<Fan> fanBottons){
        fanBottons.add(new Fan(fan1));
        fanBottons.add(new Fan(fan2));
        fanBottons.add(new Fan(fan3));
        fanBottons.add(new Fan(fan4));
        fanBottons.add(new Fan(fan5));
        fanBottons.add(new Fan(fan6));
        fanBottons.add(new Fan(fan7));
        fanBottons.add(new Fan(fan8));
        fanBottons.add(new Fan(fan9));
        fanBottons.add(new Fan(fan10));
        fanBottons.add(new Fan(fan11));
        fanBottons.add(new Fan(fan12));
        fanBottons.add(new Fan(fan13));
        fanBottons.add(new Fan(fan14));
        fanBottons.add(new Fan(fan15));
        fanBottons.add(new Fan(fan16));
        fanBottons.add(new Fan(fan17));
        fanBottons.add(new Fan(fan18));
        fanBottons.add(new Fan(fan19));
        fanBottons.add(new Fan(fan20));
        fanBottons.add(new Fan(fan21));
        fanBottons.add(new Fan(fan22));
        fanBottons.add(new Fan(fan23));
        fanBottons.add(new Fan(fan24));
    }
        
    public void setFansColor(int cant, List<Fan> fanBottons){
        for (int i = fanBottons.size()-1; i >= 6*cant; i--) {
            fanBottons.get(i).button.setBackground(Color.red);
            fanBottons.get(i).button.removeNotify();
            fanBottons.remove(i);
        }
        speedMessage = new int[fanBottons.size()];
        numActiveFans.setText(""+cant*6);
        for (int i = 0; i < 6*cant; i++) {
            fanBottons.get(i).button.setBackground(Color.white);
            speedMessage[i] = 0;
        }
    }
    
    public void fanControl(int i){
        selectedFan.setText("Fan "+(i+1)+" info");
        if (fanButtons.get(i).selected){
            fanButtons.get(i).selected = false;
            fanButtons.get(i).button.setBackground(Color.white);
        }else{
            fanButtons.get(i).selected = true;
            fanButtons.get(i).button.setBackground(Color.green);
        }
        currentSpeed.setText(""+fanButtons.get(i).speed);
        speedSlider.setValue(fanButtons.get(i).speed);
        showSpeed.setText(""+speedSlider.getValue());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFunctionality;
    private javax.swing.JLabel currentSpeed;
    private javax.swing.JLabel executing;
    private javax.swing.JButton fan1;
    private javax.swing.JButton fan10;
    private javax.swing.JButton fan11;
    private javax.swing.JButton fan12;
    private javax.swing.JButton fan13;
    private javax.swing.JButton fan14;
    private javax.swing.JButton fan15;
    private javax.swing.JButton fan16;
    private javax.swing.JButton fan17;
    private javax.swing.JButton fan18;
    private javax.swing.JButton fan19;
    private javax.swing.JButton fan2;
    private javax.swing.JButton fan20;
    private javax.swing.JButton fan21;
    private javax.swing.JButton fan22;
    private javax.swing.JButton fan23;
    private javax.swing.JButton fan24;
    private javax.swing.JButton fan3;
    private javax.swing.JButton fan4;
    private javax.swing.JButton fan5;
    private javax.swing.JButton fan6;
    private javax.swing.JButton fan7;
    private javax.swing.JButton fan8;
    private javax.swing.JButton fan9;
    private javax.swing.JLabel funAction;
    private javax.swing.JButton funExecution;
    private javax.swing.JButton funPreview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private javax.swing.JLabel numActiveFans;
    private javax.swing.JButton pressureSensor;
    private javax.swing.JLabel selectedFan;
    private javax.swing.JLabel showSpeed;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JButton stopAllFans;
    private javax.swing.JButton stopFun;
    private javax.swing.JButton updateSpeed;
    // End of variables declaration//GEN-END:variables
    }
